baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
  sass_dir: _scss

# First language in the list is default
languages: ["en", "lt"]
exclude_from_localizations: ["css", "fonts", "images"]

forms:
  contact: https://formspree.io/hello@edvinas.lt
  newsletter: https://thecoldestride.us19.list-manage.com/subscribe/post?u=8b744ccf83c43d9263df1ee75&amp;id=8be1c78f4c

analytics:
  ga:
    id: UA-125482278-1
